### ISSUE TITLE
Remove Agent port exposition

### ISSUE THREAD

**Issue by ignacio-penas** [nuvlaedge/deployment#82]
The agent API server is only accessed locally and doesn't need to be exposed. 

Remove exposed AGENT_PORT in favor of internal docker port assignment. AGENT API is only for local usage and can be accessed within the nuvlaedge internal network. 

Peripheral manager integrated with the agent. Forward steps consist on integrating the peripherals themselves:

- [x] nuvlaedge/peripheral-manager-network#8
- [x] nuvlaedge/peripheral-manager-bluetooth#8
- [x] nuvlaedge/peripheral-manager-modbus#6
- [x] nuvlaedge/peripheral-manager-gpu#11
- [x] nuvlaedge/peripheral-manager-usb#17
- [x] nuvlaedge/security#12

**Comment by ignacio-penas** [comment]
Peripheral manager integrated with the agent. Forward steps consist on integrating the peripherals themselves:

- [ ] Network
- [ ] Bluetooth
- [ ] Modbus
- [ ] GPU
- [ ] USB
